emqx/ekka

Makefile, README.md, etc/ekka.conf.example, src/ekka.app.src, src/ekka.erl, src/ekka_app.erl, src/ekka_autoclean.erl, src/ekka_autocluster.erl, src/ekka_autoheal.erl, src/ekka_boot.erl, src/ekka_cluster.erl, src/ekka_cluster_dns.erl, src/ekka_cluster_etcd.erl, src/ekka_cluster_k8s.erl, src/ekka_cluster_mcast.erl, src/ekka_cluster_static.erl, src/ekka_cluster_strategy.erl, src/ekka_cluster_sup.erl, src/ekka_guid.erl, src/ekka_httpc.erl, src/ekka_membership.erl, src/ekka_mnesia.erl, src/ekka_node.erl, src/ekka_node_monitor.erl, src/ekka_node_ttl.erl, src/ekka_sup.erl
1. Update README.md
2. Add ekka:is_member/1, ekka:nodelist/0 APIs
=> Version 0.3

etc/ekka.conf.example, etc/ekka.config.example, priv/ekka.schema, src/ekka_cluster_etcd.erl, src/ekka_httpc.erl
Add etcd client certificate method.
=> Add etcd client certificate

src/ekka_mnesia.erl
fix case clause for https://github.com/emqx/ekka/blob/2753f147168217dbe404672fba741aee309d2dc3/src/ekka.erl#L53
=> return typo in error reason

src/ekka_locker.erl
While remote node is booting, the acquire_lock/2 might fail because the ETS table has not been created at that moment.
=> Fix acquire_lock crash while remote node rebooting

src/ekka_locker.erl
**A new tag is required, and need to be push to hex again.**
=> Fix unlock crash

.github/workflows/run_test_case.yaml, .gitignore, Makefile, rebar.config, rebar.config.script, src/ekka.app.src, src/ekka_autoheal.erl, src/ekka_dist.erl, src/ekka_httpc.erl, test/ekka_autoclean_SUITE.erl, test/ekka_autocluster_SUITE.erl, test/ekka_autoheal_SUITE.erl, test/ekka_cluster_etcd_SUITE.erl, test/ekka_ct.erl, test/ekka_epmd_SUITE.erl, test/mod_etcd.erl, test/mod_k8s_api.erl
- Add github action/ coveralls for tests
- Remove the default envs
- Improve test cases compiling warnings
=> Fix the offset over the limit of a ethernet interface

src/ekka_dist.erl
there is no need to update appup file because it only affects remote console.
=> feat(dist): Allow remsh to use a wild port range

.gitignore, Makefile, include/ekka.hrl, src/ekka.erl, src/ekka_autoclean.erl, src/ekka_autoheal.erl, src/ekka_cluster.erl, src/ekka_cluster_strategy.erl, src/ekka_locker.erl, src/ekka_mnesia.erl, src/ekka_node_monitor.erl
A superficial fix for the dialyzer warnings.
=> chore(dialyzer): Fix dialyzer warnings

src/ekka_mnesia.erl, src/ekka_rlog.erl, src/ekka_rlog_activity.erl, src/ekka_rlog_bootstrapper.erl, src/ekka_rlog_config.erl, src/ekka_rlog_lib.erl, src/ekka_rlog_replica.erl, src/ekka_rlog_server.erl, src/ekka_rlog_sup.erl, src/ekka_rlog_tab.erl
=> Refactoring

src/ekka.app.src, src/ekka_autoclean.erl, src/ekka_mnesia_null_storage.erl, src/ekka_rlog.erl, src/ekka_rlog_activity.erl, src/ekka_rlog_bootstrapper.erl, src/ekka_rlog_config.erl
Applied remarks from @gorillainduction sans splitting bootstrapper module into server and client part, that one deserves a separate PR.
=> chore(rlog): Apply remarks

src/ekka_mnesia.erl, src/ekka_rlog.erl, src/ekka_rlog_lib.erl
No functional change, just moved some code between the modules.
=> refactor(rlog): Move helper functions to the library module

doc/rlog.md, rebar.config, src/ekka_mnesia.erl, src/ekka_mnesia_null_storage.erl, src/ekka_rlog.erl, src/ekka_rlog.hrl, src/ekka_rlog_activity.erl, src/ekka_rlog_agent.erl, src/ekka_rlog_bootstrapper.erl, src/ekka_rlog_config.erl, src/ekka_rlog_lb.erl, src/ekka_rlog_lib.erl, src/ekka_rlog_replica.erl, src/ekka_rlog_schema.erl, src/ekka_rlog_server.erl, src/ekka_rlog_shard_sup.erl, src/ekka_rlog_status.erl, src/ekka_rlog_sup.erl, src/ekka_rlog_tab.erl, test/ekka_mnesia_SUITE.erl
Move away from compile-time shard configuration to a fully dynamic one.
=> Dynamic shards

src/ekka.erl, src/ekka_rlog.erl, src/ekka_rlog_schema.erl, src/ekka_rlog_server.erl
Fix a race condition in the shard initialization procedure on the core node
=> fix(rlog): Fix wait_for_shards on the core node

src/ekka_node_monitor.erl
=> fix(autoheal): Send heartbeats to the stopped nodes

etc/ekka.conf.example, priv/ekka.schema, src/ekka_cluster_dns.erl, test/ekka_cluster_dns_SUITE.erl
same https://github.com/emqx/ekka/pull/132
=> add srv for dns 

src/ekka.appup.src
Missing module caught by emqx CI.
=> chore(appup): update appup

src/ekka.appup.src, src/ekka_dist.erl
see https://github.com/emqx/ekka/pull/166
=> fix(ekka_dist): support SSL

rebar.config, src/ekka_cluster_dns.erl, test/ekka_autocluster_SUITE.erl
=> feat(autocluster): Support discovery via AAAA DNS records

src/ekka.app.src, src/ekka.appup.src, src/ekka_autocluster.erl, src/ekka_cluster_etcd.erl
Relates to: EMQX-10631 and https://github.com/emqx/emqx/issues/11312
=> fix etcd lock issues

src/ekka_autocluster.erl, src/ekka_cluster.erl, test/ekka_autocluster_SUITE.erl
Part of https://emqx.atlassian.net/browse/EMQX-12493
=> feat: add `singleton` strategy

rebar.config
=> chore: upgrade to mria 0.8.10

rebar.config
https://github.com/zhongwencool/eetcd/pull/66
We have built multiple emqx clusters in the test environment, all of which are based on the same etcd service. We found that these different emqx cluster machines will join each other.
https://askemq.com/t/topic/12193
=> fix: bad get_prefix_range_end
