etc/ekka.conf.example
priv/ekka.schema
src/ekka_cluster_k8s.erl

add new address type "hostname", and optional hostname_suffix configuration item and does the same as rabbitmq in its k8s cluster discovery. 
ekka will use hostname get from apiserver and configured hostname_suffix to build nodename, in this way, every emqx node will have a static node name when deployed using k8s statefulset.  data will survice pod recreate.

Support static node name for k8s cluster discovery

---

README.md
etc/ekka.conf.example
etc/ekka.config.example
priv/ekka.schema
src/ekka.erl
src/ekka_dist.erl
src/ekka_epmd.erl

- Add ekka_epmd, ekka_dist modules.
- Add 'cluster.proto_dist' config.
See:
http://erlang.org/pipermail/erlang-questions/2015-December/087013.html
https://www.erlang-solutions.com/blog/erlang-and-elixir-distribution-without-epmd.html

Ekka cluster without epmd.

---

src/ekka_guid.erl
src/ekka_httpc.erl

1. Fix the ekka_guid failures on OTP 23
> In OTP 23 distribution flag DFLAG_BIG_CREATION became mandatory. All pids are now encoded using NEW_PID_EXT, even external pids received as PID_EXT from older nodes.
>
> see: http://erlang.org/doc/apps/erts/erl_ext_dist.html#new_pid_ext
2. Eliminate compiling warnings on OTP 23

fix(ekka_guid): support NEW_PID_EXT to generate guid

---

src/ekka_mnesia.erl

ekka_mnesia should retry if wait for mnesia tables timeout.
This avoids the node runs into inconsistent states as the other nodes
in the cluster in case of node failed to load the tables eventually.
Also, avoid the node boots to later stages before the master node starts
which makes the node not able to self-recover without a manual restart.
fix the emqx issue: https://github.com/emqx/emqx/issues/4535

fix(ekka_mnesia): retry if wait for table timeout

---

Makefile
src/ekka_rlog_agent.erl
test/concuerror_tests.erl

No functional change, just adding a new Concuerror model

test(rlog): Add a concuerror model of the dirty bootstrap procedure

---

src/ekka_mnesia.erl
src/ekka_rlog_agent.erl
src/ekka_rlog_lb.erl
src/ekka_rlog_lib.erl
src/ekka_rlog_server.erl
src/ekka_rlog_status.erl
test/ekka_ct.erl
test/ekka_mnesia_SUITE.erl
test/ekka_mnesia_error_injection_SUITE.erl

`ekka_mnesia:running_nodes()` now includes replicant nodes. Also this PR fixes some unstable testcases

fix ekka_mnesia:running_nodes

---

src/ekka_mnesia.erl

fix https://github.com/emqx/emqx/issues/5254
I have manually tested in a minikube env.

fix: dup calls to force mnesia schema merge from remote node

---

doc/rlog.md
src/ekka_mnesia.erl
src/ekka_rlog.erl
src/ekka_rlog.hrl
src/ekka_rlog_config.erl
src/ekka_rlog_lib.erl
src/ekka_rlog_replica.erl
src/ekka_rlog_schema.erl
src/ekka_rlog_server.erl
test/ekka_mnesia_SUITE.erl
test/ekka_mnesia_test_util.erl
test/test_src/ekka_helper_tab.erl
test/test_src/ekka_transaction_gen.erl

A few changes that finally made it work with the current version of EMQ X:
1) Implement handling of local_content tables
2) Drop support for `-rlog_shard` annotation, and keep only one way of defining tables
3) Replicants' schema is forcibly converged to the core nodes' view

feat(rlog): Implement support for local_content tables

---

src/ekka_cluster_etcd.erl

fix regression,
check if SSL is disabled or not and also prevent the enable parm leak to SSL options.
Without this check, there seems no way to disable the SSL.

fix(etcd): check ssl enable

---

src/ekka.appup.src
src/ekka_locker.erl

```
2021-11-09 08:18:09.568 [error] ** Generic server emqx_cm_locker terminating 
** Last message in was {'DOWN',#Ref<0.1914890529.1843920897.137756>,process,
<59068.27251.351>,killed}
** When Server state == {state,emqx_cm_locker,
{lease,15000,
{ok,
{interval,#Ref<0.1914890528.4267704322.100681>}}},
true}
** Reason for termination ==
** {{badmap,true},
[{maps,find,[<59068.27251.351>,true],[]},
{ekka_locker,handle_info,2,
[{file,"/Users/liuxy/code/emqx-enterprise-rel/_build/emqx/lib/ekka/src/ekka_locker.erl"},
{line,283}]},
{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,637}]},
{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,711}]},
{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,259}]}]}
```

fix(locker): the locker crashed when trying to release locks

---

src/ekka.appup.src

We're doing this to remove some missing change warnings when updating
emqx v4.3.10.

chore(appup): bump appup and version to 0.8.1.6

---

src/ekka_autocluster.erl
src/ekka_boot.erl
test/ekka_autocluster_SUITE.erl
test/ekka_boot_SUITE.erl
test/mod_etcd.erl

This adds support for core node discovery for mria, as it will help
operators configure their nodes when using RLOG as the DB Backend in
mria.
Related to emqx/mria#38 .

feat(core_node_discovery): add mria core node discovery callback

---

src/ekka_autocluster.erl
test/ekka_autocluster_SUITE.erl

Occasionally, the cluster strategy lock may raise some error, like
timing out during a `gen_server:call`.  In this case, it might
deadlock and prevent the lock from being acquired again.
```
Ekka(AutoCluster): Discover error: {timeout,{gen_server,call,[ekka_cluster_etcd,lock,5000]}}, [{gen_server,call,3,[{file,"gen_server.erl"},{line,247}]},{ekka_autocluster,'-discover_and_join/0-fun-0-',2,[{file,"/emqx/deps/ekka/src/ekka_autocluster.erl"},{line,81}]},{ekka_autocluster,'-run/1-fun-0-',1,[{file,"/emqx/deps/ekka/src/ekka_autocluster.erl"},{line,48}]}]
```
This can prevent or hinder the cluster from forming.

fix: unlock on lock error

---

src/ekka_autocluster.erl
src/ekka_cluster_etcd.erl
test/ekka_autocluster_SUITE.erl

Sometimes, for still unknown reasons, core nodes can successfully join
the ekka/mria cluster, but fail to announce themselves to the service
discovery.  This leads to an incorrect value reported by the core node
discovery callback, which relies on the announce mechanism. In turn,
that prevents replicants from joining the cluster, because they check
that announced list against the db nodes reported by mria, and refuse
to accept such list because of the "unknown" nodes from mria.
So, we make the autocluster also check if the node is successfully
registered and, if not, retry to discover and join the cluster,
hopefully announcing the node correctly in the process.
Example:
```
2022-03-08T14:21:48.129201-03:00 [error] '$kind': mria_lb_core_discovery_divergent_cluster, line: 171, mfa: …
```

fix: ensure node is registered during autocluster

---

src/ekka_cluster_etcd.erl
test/ekka_cluster_etcd_SUITE.erl
test/ekka_ct.erl

If the `ekka_cluster_etcd` process itself dies, the `eetcd` client
will keep running, and when the supervisor tries to restart
`ekka_cluster_etcd`, it'll fail because the client is already running.
By closing any possibly existing connections before connecting again,
the supervisor may restart it successfully.
```
2022-02-08T14:57:06.452469+00:00 [error] Supervisor: {local,ekka_cluster_sup}. Context: start_error. Reason: {{badmatch,{error,[{{"etcd0.int.thalesmg",2379},already_started}]}},[{ekka_cluster_etcd,init,1,[{file,"/emqx/deps/ekka/src/ekka_cluster_etcd.erl"},{line,337}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,423}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,390}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}. Offender: …
```

fix: ensure etcd connection is closed at startup

---

src/ekka_mnesia.erl
test/ekka_mnesia_SUITE.erl

print some diagnosis logging like 
```
=WARNING REPORT==== 5-Apr-2022::19:08:24.146845 ===
Check down_nodes should get [] but get ['n2@127.0.0.1']
Table test_tab_1 is waiting for one of the nodes: ['n2@127.0.0.1'] 
=WARNING REPORT==== 5-Apr-2022::19:08:29.299556 ===
Check down_nodes should get [] but get ['n2@127.0.0.1']
Table test_tab_1 is waiting for one of the nodes: ['n2@127.0.0.1'] 
=WARNING REPORT==== 5-Apr-2022::19:08:29.425585 ===
Table test_tab_1 is loading from local disc copy 
=WARNING REPORT==== 5-Apr-2022::19:08:29.433342 ===
Table test_tab_1 is loading from remote node 'n1@127.0.0.1'
```

feat(mnesia): diagnosis logging for wait_for_table

---

src/ekka.appup.src
src/ekka_autocluster.erl
test/ekka_autocluster_SUITE.erl
test/mod_etcd.erl

To avoid split-brain scenarios, we retry the autocluster procedure if
there still nodes being discovered outside the cluster.

fix(autocluster): retry autocluster if there are nodes outside cluster

---

rebar.config

- ~~do not wait on shard during transaction.~~
- reduces some message log levels about waiting for shards to
debug on cores.
https://github.com/emqx/mria/pull/84
https://github.com/emqx/mria/pull/86

chore: bump mria -> 0.2.5

---

src/ekka.appup.src

will re-tag 0.13.1 (not used anywhere so far).

fix(appup): fix app vsn strings in appup.src

---

rebar.config

ZSTD fix.
https://github.com/emqx/mnesia_rocksdb/pull/6

chore: bump mria -> `0.2.12`

---

rebar.config

see: https://github.com/emqx/mria/pull/109

chore: upgrade mria to 0.2.16 to support mria:dirty_update_counter/{2,3}

---

rebar.config

no functional changes, there are pre-built binary packages for more platforms

chore: bump mria to 0.4.1

---

README.md
data/app.etcd.config
data/app.mcast.config
etc/ekka.conf.example
etc/ekka.config.example
priv/ekka.schema
test/ekka_SUITE_data/ekka.config

This option is no longer used by ekka, as it has been moved to mria.

refactor: remove references to autoclean

---

.github/workflows/run_test_case.yaml
rebar.config
test/ekka_autocluster_SUITE.erl

https://github.com/emqx/erlang-rocksdb/releases/tag/1.8.0-emqx-1
also bumps builder images and distros
will tag 0.15.6

chore: bump mria -> 0.5.8

---

rebar.config
src/ekka.app.src
src/ekka.appup.src

Also prepare `ekka` 0.15.10 release.

chore: bump mria to 0.6.0

---

src/ekka_autocluster.erl

2023-09-12T10:07:25.471551+00:00 [error] FORMAT ERROR: "Ekka(AutoCluster): Bad nodes found: ~p, ResL: " - [['emqx-dev@emqx-dev-1.emqx-dev-headless.xyz-mqtt-emqx.svc.cluster.local'],[{member,'emqx-dev@emqx-dev-0.emqx-dev-headless.xyz-mqtt-

fix(autocluster): membership rpc log format error

---

rebar.config

Included updates:
- https://github.com/emqx/mria/pull/160
- https://github.com/emqx/mria/pull/161
- https://github.com/emqx/mria/pull/162

chore: bump mria to 0.6.3

---

rebar.config

Mria 0.8.0 release implements `mria:match_delete/2` function

chore: upgrade to mria 0.8.0

---

src/ekka.erl

Users are advised to manage tables explicitly as part of applications' startup routines. Dropping this feature might help to greatly reduce the time it takes ekka to start.

refactor: disable mnesia boot phase altogether

---

rebar.config
src/ekka.erl
src/ekka_autocluster.erl

Depends on: https://github.com/emqx/mria/pull/177
EMQX PR: https://github.com/emqx/emqx/pull/12799

EMQX-11826 prevent left node from rejoining

---

.github/workflows/run_test_case.yaml
src/ekka.appup.src
src/ekka_autoheal.erl
src/ekka_node_monitor.erl
test/ekka_autoheal_SUITE.erl

Fixes [EMQX-13693](https://emqx.atlassian.net/browse/EMQX-13693).

fix(autoheal): attempt healing complex asymmetric partitions

---

rebar.config

Includes emqx/mria#184.
Fixes [EMQX-13588](https://emqx.atlassian.net/browse/EMQX-13588).

chore: bump `mria` to 0.8.11

---

.github/workflows/run_test_case.yaml
rebar.config
src/ekka.app.src
src/ekka_cluster_etcd.erl
src/ekka_httpc.erl
test/mod_etcd.erl

chore: bump dependencies to OTP-27-ready versions

---

rebar.config

Changes:
- 0.8.14: fixed EXIT messages leak
- 0.8.15: fixed build for macOS 15

fix: upgrade mria from 0.8.13 to 0.8.15.

---

rebar.config
src/ekka.app.src
src/ekka_cluster_k8s.erl
src/ekka_httpc.erl
test/ekka_cluster_etcd_SUITE.erl
test/ekka_cluster_k8s_SUITE.erl
test/ekka_httpc_SUITE.erl

Use hackney client instead of httpc.

feat(httpc): Switch to hackney

---

src/ekka_locker.erl
test/ekka_locker_SUITE.erl

- acquire/release should return false if result list is empty or all nodes are down.
- failed rpc call should be treated as negative as well. a common error is rpc timeout.
without this fix, it may leave dead locks in the EMQX cluster as the 'locks' are inconsistent in the cluster. 
there is a leak detection `check_lease` but it takes many secends to detect these dead locks.

fix(locker): return false when no available nodes or rpc timeout
